# -*- coding: utf-8 -*-
"""02_graph_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwfeyanvD8B5bxKAOvRHE1GVP7D-UKQR

# Graph Extraction (Two-Tier Chain & Strict Biological Ontology)

Experimnet untuk menarik semua teks **Chunks** yang sudah dibuat di pengujian sebelumnya, lalu mengeksekusi metode ekstraksi *Knowledge Graph* (GraphRAG) menggunakan *Two-Tier Chain*

### Install Library
"""

!pip install supabase requests

"""### Konfigurasi dan Inisialisasi Model"""

import os
import requests
import json
import time
import re
from supabase import create_client, Client

# --- CONFIGURATION ---
SUPABASE_URL = "https://wptyvhadubupeqyhrvbw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwdHl2aGFkdWJ1cGVxeWhydmJ3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTgwOTIwNCwiZXhwIjoyMDg3Mzg1MjA0fQ.3FQA3REjN5JyiFTDT5y5f27KwdPOAF86rSqPiyQfNp8"
MISTRAL_API_KEY = "qaCNQYWEJyPFaCZt6Z8AMoGLc5HrIDsk"
MISTRAL_URL = "https://api.mistral.ai/v1/chat/completions"

try:
    supabase_client: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    print("Supabase terhubung!")
except Exception as e:
    supabase_client = None
    print("Supabase Error:", e)

"""### Arsitektur Utama (Two-Tier Chain)"""

def call_mistral(system_prompt: str, user_prompt: str, temperature: float = 0.1, response_format=None):
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {MISTRAL_API_KEY}"
    }
    data = {
        "model": "mistral-small-latest",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": temperature
    }
    if response_format:
        data["response_format"] = response_format

    max_retries = 3
    for i in range(max_retries):
        try:
            resp = requests.post(MISTRAL_URL, headers=headers, json=data)
            resp.raise_for_status()
            return resp.json()['choices'][0]['message']['content'].strip()
        except Exception as e:
            print(f"API Error (percobaan {i+1}): {e}")
            time.sleep(10) # 10 detik delay jika terjadi error limitasi API
    return ""

# --- TIER 1: Peringkasan Khusus Medis ---
def summarize_medical_text(raw_text: str) -> str:
    system_prompt = "You are a strict botanical and pharmacological expert. Summarize the following text by prioritizing and preserving all exact scientific names of plants, chemical compounds, body parts, diseases, and pharmacological verbs. Do not lose any medical context."
    return call_mistral(system_prompt, f"Text to summarize:\n{raw_text}", temperature=0.1)

# --- TIER 2: Ekstraksi Berdasarkan Strict Ontology ---
def extract_biological_graph(summary_text: str) -> list:
    system_prompt = """
You are an expert data extractor for a Knowledge Graph. Extract relationships from the text strictly adhering to the following ontology:

ALLOWED ENTITY TYPES: 'Plant', 'Compound', 'Disease', 'Symptom', 'BodyPart'.

ALLOWED RELATION TYPES: 'contains' (Plant -> Compound), 'cures' (Plant/Compound -> Disease), 'inhibits' (Compound -> Symptom/Disease), 'causes' (Disease -> Symptom).

Return ONLY a valid JSON array of arrays in this exact format:
[["Entity1", "EntityType1", "Relation", "Entity2", "EntityType2"]]

Do not invent new relation types.
"""
    # Kita panggil mode JSON dari Mistral (bisa menggunakan response_format={'type': 'json_object'} tetapi karena kita meminta Array langsung,
    # seringkali JSON response type memaksa hasil berupa Object dict {}. Oleh sebab itu biarkan default dan kita Parse Regex JSON).
    raw_output = call_mistral(system_prompt, f"Text to extract:\n{summary_text}", temperature=0.0)

    try:
        # Membersihkan tanda Markdown backticks (```json ... ```)
        clean_out = re.sub(r"^```json\n?", "", raw_output)
        clean_out = re.sub(r"\n?```$", "", clean_out)

        # Mencoba mem Parsing menjadi array Python
        parsed_json = json.loads(clean_out)
        if isinstance(parsed_json, list):
            return parsed_json
        return []
    except Exception as e:
        print("Gagal parse JSON graph:", e)
        print("Teks Mentah LLM:\n", raw_output)
        return []

"""### Eksekutor Ekstraksi Graph Batch"""

# --- CELL: KNOWLEDGE GRAPH EXTRACTION (EXPERIMENT 2) ---

def process_and_save_graphs_v2(chunk_table_name: str, graph_table_name: str, limit_per_journal=5):
    """
    Ekstraksi Knowledge Graph khusus untuk tabel V2 (Experiment 2).
    """
    # 1. Ambil list jurnal yang sudah diproses di V2
    res_journals = supabase_client.table('journals_experiment').select('id, title').execute()
    journals = res_journals.data

    if not journals:
        print("❌ Tidak ada jurnal di Database!")
        return

    print(f"\n🚀 MEMULAI EKSTRAKSI GRAF: {chunk_table_name} -> {graph_table_name}")
    print(f"⚙️ Limit: {limit_per_journal} chunks per jurnal (Gratisan Mistral Mode)")

    for journal in journals:
        j_id = journal['id']
        j_title = journal['title']

        # Opsi: Bersihkan data graf lama untuk jurnal ini di tabel target jika ingin refresh
        # supabase_client.table(graph_table_name).delete().eq('journal_id', j_id).execute()

        # 2. Ambil chunk dari tabel V2 terkait
        res_chunks = supabase_client.table(chunk_table_name).select('id, text_content, chunk_index')\
            .eq('journal_id', j_id)\
            .order('chunk_index')\
            .limit(limit_per_journal).execute()

        chunks = res_chunks.data
        if not chunks:
            continue

        print(f"\n>>> Jurnal: {j_title[:50]}...")
        total_inserted = 0

        for chunk in chunks:
            idx = chunk['chunk_index']
            print(f"   - Processing Chunk Index: {idx} (ID: {chunk['id'][:8]})")

            raw_text = chunk['text_content']
            if len(raw_text) < 100: # Filter teks sampah
                continue

            try:
                # --- Tier 1: Medical Summary ---
                # (Pastikan fungsi summarize_medical_text sudah didefinisikan sebelumnya)
                summary = summarize_medical_text(raw_text)
                if not summary: continue

                time.sleep(3) # Jeda untuk Rate Limit Mistral

                # --- Tier 2: Ontology Extraction ---
                # (Pastikan fungsi extract_biological_graph sudah didefinisikan sebelumnya)
                graph_data = extract_biological_graph(summary)

                # --- Tier 3: Insert to V2 Graph Table ---
                inserted_in_chunk = 0
                for rel in graph_data:
                    # Validasi struktur Array ["Entity1", "Type1", "Relation", "Entity2", "Type2"]
                    if isinstance(rel, list) and len(rel) == 5:
                        supabase_client.table(graph_table_name).insert({
                            "journal_id": j_id,
                            "chunk_id": chunk['id'],
                            "entity_1": rel[0],
                            "type_1": rel[1],
                            "relation": rel[2],
                            "entity_2": rel[3],
                            "type_2": rel[4]
                        }).execute()
                        inserted_in_chunk += 1

                print(f"      ✅ Berhasil: {inserted_in_chunk} relasi ditemukan.")
                total_inserted += inserted_in_chunk

                # Delay antar chunk agar API stabil
                time.sleep(5)

            except Exception as e:
                print(f"      ⚠️ Error pada chunk {idx}: {e}")
                time.sleep(10) # Istirahat lebih lama jika error

        print(f"🏁 Selesai: {j_title[:30]}. Total Graf: {total_inserted}")

"""---

### 1. Chunk Kalimat
"""

process_and_save_graphs_v2("chunk_sentence2", "graph_sentence", limit_per_journal=60)

"""### 2. Chunk Kata"""

# Eksekusi Kata/Token
process_and_save_graphs_v2("chunk_word2", "graph_word", limit_per_journal=60)

"""### 3. Chunk Karakter

"""

process_and_save_graphs_v2("chunk_character2", "graph_character", limit_per_journal=60)

import pandas as pd
import numpy as np

def fetch_all_graph_data(table_name):
    """Fungsi untuk mengambil seluruh data dari Supabase melampaui limit 1000."""
    all_data = []
    limit = 1000
    offset = 0

    while True:
        res = supabase_client.table(table_name).select("entity_1, relation, entity_2")\
            .range(offset, offset + limit - 1).execute()

        data = res.data
        if not data:
            break

        all_data.extend(data)
        if len(data) < limit: # Berarti sudah sampai halaman terakhir
            break
        offset += limit

    return all_data

def get_kg_statistics_full():
    tables = {
        "Sentence Split": "graph_sentence",
        "Word Split": "graph_word",
        "Character Split": "graph_character"
    }

    summary_data = []
    print("📊 Memulai Analisis Perbandingan Knowledge Graph (Full Data Sync)...")

    for method_name, table_name in tables.items():
        try:
            # Mengambil data menggunakan fungsi pagination agar > 1000 baris
            data = fetch_all_graph_data(table_name)

            if not data:
                print(f"⚠️ Tabel {table_name} kosong, skip.")
                continue

            df_graph = pd.DataFrame(data)

            # Menghitung Unique Nodes
            all_entities = pd.concat([df_graph['entity_1'], df_graph['entity_2']]).dropna()
            unique_nodes = len(all_entities.unique())

            # Menghitung Unique Edges
            unique_edges = len(df_graph.drop_duplicates(subset=['entity_1', 'relation', 'entity_2']))

            summary_data.append({
                "Method": method_name,
                "Total Triplets": len(df_graph),
                "Unique Nodes": unique_nodes,
                "Unique Edges": unique_edges,
                "Connectivity (Edge/Node)": round(unique_edges / unique_nodes, 2) if unique_nodes > 0 else 0,
                "Most Frequent Entity": all_entities.mode()[0] if not all_entities.empty else "-"
            })

        except Exception as e:
            print(f"❌ Error saat menganalisis {table_name}: {e}")

    # Tampilkan Tabel Final
    if summary_data:
        df_summary = pd.DataFrame(summary_data)
        print("\n" + "="*95)
        print("🏆 PERBANDINGAN STRUKTUR KNOWLEDGE GRAPH - DATA LENGKAP")
        print("="*95)
        print(df_summary.to_string(index=False))
        print("="*95)
    else:
        print("❌ Tidak ada data graf yang ditemukan.")

# Jalankan Analisis Full Data
get_kg_statistics_full()