import { Sparkles, Copy, Check, Bot } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { motion } from "framer-motion";
import { useState } from "react";
import { Button } from "@/components/ui/button";

export const AIAnswerCard = ({ answer }: { answer: string }) => {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(answer);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="rounded-3xl border border-emerald-500/20 bg-black/20 backdrop-blur-xl overflow-hidden relative group"
        >
            {/* Header */}
            <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-emerald-500 via-teal-500 to-emerald-500 opacity-50" />

            <div className="p-6 md:p-8">
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500/20 to-teal-500/20 border border-emerald-500/30 flex items-center justify-center">
                            <Bot className="w-5 h-5 text-emerald-400" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold text-white tracking-tight">AI Analysis Result</h2>
                            <p className="text-xs text-emerald-400/60 font-mono">GENERATED BY HYBRID RAG</p>
                        </div>
                    </div>
                    <Button
                        variant="ghost"
                        size="sm"
                        onClick={handleCopy}
                        className="text-gray-400 hover:text-white hover:bg-white/5"
                    >
                        {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                    </Button>
                </div>

                <div className="prose prose-invert prose-emerald max-w-none leading-relaxed">
                    <ReactMarkdown components={{
                        p: ({ children }) => <p className="mb-4 text-gray-300 leading-7">{children}</p>,
                        strong: ({ children }) => <strong className="text-emerald-300 font-semibold">{children}</strong>,
                        ul: ({ children }) => <ul className="list-disc list-outside ml-4 mb-4 space-y-1 text-gray-300">{children}</ul>,
                        li: ({ children }) => <li className="pl-1">{children}</li>,
                        h3: ({ children }) => <h3 className="text-lg font-bold text-white mt-6 mb-3">{children}</h3>
                    }}>{answer}</ReactMarkdown>
                </div>
            </div>

            {/* Futuristic Decor */}
            <div className="absolute top-0 right-0 p-4 opacity-20 pointer-events-none">
                <Sparkles className="w-24 h-24 text-emerald-500 blur-xl" />
            </div>
        </motion.div>
    );
};
